export type EditableThemeItemKind = "workbench" | "textMate" | "semantic";

export type ThemeRoleName =
  | "base"
  | "surface"
  | "surfaceAlt"
  | "surfaceElevated"
  | "accent"
  | "accentAlt"
  | "accentMuted"
  | "textPrimary"
  | "textSecondary"
  | "textMuted"
  | "success"
  | "warning"
  | "error"
  | "info"
  | "diffAdded"
  | "diffModified"
  | "diffDeleted";

export interface EditableThemeItem {
  kind: EditableThemeItemKind;
  category: string;
  id: string;
  label: string;
  description: string;
  defaultRole: ThemeRoleName;
  advanced?: boolean;
  scopes?: string[];
  semanticSelector?: string;
}

// Workbench

export const WORKBENCH_EDITABLE_ITEMS: EditableThemeItem[] = [
  {
    kind: "workbench",
    category: "Global",
    id: "foreground",
    label: "Global foreground",
    description: "Default UI text",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Global",
    id: "disabledForeground",
    label: "Disabled foreground",
    description: "Disabled text and icons",
    defaultRole: "textMuted",
  },
  {
    kind: "workbench",
    category: "Global",
    id: "focusBorder",
    label: "Focus border",
    description: "Focus outline",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Global",
    id: "errorForeground",
    label: "Error foreground",
    description: "Generic error text",
    defaultRole: "error",
  },
  {
    kind: "workbench",
    category: "Global",
    id: "icon.foreground",
    label: "Icon foreground",
    description: "Default UI icon color",
    defaultRole: "textSecondary",
  },
  {
    kind: "workbench",
    category: "Window",
    id: "window.activeBorder",
    label: "Active window border",
    description: "Focused window border",
    defaultRole: "accentMuted",
  },
  {
    kind: "workbench",
    category: "Window",
    id: "window.inactiveBorder",
    label: "Inactive window border",
    description: "Unfocused window border",
    defaultRole: "surfaceAlt",
  },
  {
    kind: "workbench",
    category: "Title Bar",
    id: "titleBar.activeBackground",
    label: "Active title bar",
    description: "Window title bar background",
    defaultRole: "surfaceAlt",
  },
  {
    kind: "workbench",
    category: "Title Bar",
    id: "titleBar.activeForeground",
    label: "Active title text",
    description: "Window title text",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Title Bar",
    id: "titleBar.inactiveBackground",
    label: "Inactive title bar",
    description: "Unfocused title background",
    defaultRole: "surface",
  },
  {
    kind: "workbench",
    category: "Activity Bar",
    id: "activityBar.background",
    label: "Activity bar background",
    description: "Primary side rail background",
    defaultRole: "surfaceAlt",
  },
  {
    kind: "workbench",
    category: "Activity Bar",
    id: "activityBar.foreground",
    label: "Activity bar foreground",
    description: "Active activity icon",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Activity Bar",
    id: "activityBar.inactiveForeground",
    label: "Activity bar inactive",
    description: "Inactive activity icons",
    defaultRole: "textMuted",
  },
  {
    kind: "workbench",
    category: "Activity Bar",
    id: "activityBar.activeBorder",
    label: "Activity active border",
    description: "Active activity indicator",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Activity Bar",
    id: "activityBarBadge.background",
    label: "Activity badge background",
    description: "Badge background",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Sidebar",
    id: "sideBar.background",
    label: "Sidebar background",
    description: "Sidebar main background",
    defaultRole: "surface",
  },
  {
    kind: "workbench",
    category: "Sidebar",
    id: "sideBar.foreground",
    label: "Sidebar foreground",
    description: "Sidebar text",
    defaultRole: "textSecondary",
  },
  {
    kind: "workbench",
    category: "Sidebar",
    id: "sideBarTitle.foreground",
    label: "Sidebar title",
    description: "Sidebar section title",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Sidebar",
    id: "sideBarSectionHeader.background",
    label: "Sidebar section header",
    description: "Accordion header background",
    defaultRole: "surfaceElevated",
  },
  {
    kind: "workbench",
    category: "Status Bar",
    id: "statusBar.background",
    label: "Status bar background",
    description: "Bottom status bar",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Status Bar",
    id: "statusBar.foreground",
    label: "Status bar foreground",
    description: "Status bar text",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Status Bar",
    id: "statusBar.debuggingBackground",
    label: "Debug status background",
    description: "Status bar in debug mode",
    defaultRole: "warning",
  },
  {
    kind: "workbench",
    category: "Editor Groups",
    id: "editorGroup.background",
    label: "Editor group background",
    description: "Editor area background",
    defaultRole: "base",
  },
  {
    kind: "workbench",
    category: "Tabs",
    id: "editorGroupHeader.tabsBackground",
    label: "Tabs background",
    description: "Tab strip background",
    defaultRole: "surface",
  },
  {
    kind: "workbench",
    category: "Tabs",
    id: "tab.activeBackground",
    label: "Active tab background",
    description: "Selected tab background",
    defaultRole: "base",
  },
  {
    kind: "workbench",
    category: "Tabs",
    id: "tab.activeForeground",
    label: "Active tab foreground",
    description: "Selected tab text",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Tabs",
    id: "tab.inactiveBackground",
    label: "Inactive tab background",
    description: "Unselected tab background",
    defaultRole: "surface",
  },
  {
    kind: "workbench",
    category: "Tabs",
    id: "tab.inactiveForeground",
    label: "Inactive tab foreground",
    description: "Unselected tab text",
    defaultRole: "textMuted",
  },
  {
    kind: "workbench",
    category: "Tabs",
    id: "tab.activeBorder",
    label: "Active tab border",
    description: "Selected tab accent border",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Editor",
    id: "editor.background",
    label: "Editor background",
    description: "Code editor background",
    defaultRole: "base",
  },
  {
    kind: "workbench",
    category: "Editor",
    id: "editor.foreground",
    label: "Editor foreground",
    description: "Default code text",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Editor",
    id: "editor.lineHighlightBackground",
    label: "Line highlight",
    description: "Current line background",
    defaultRole: "surfaceElevated",
  },
  {
    kind: "workbench",
    category: "Editor",
    id: "editor.selectionBackground",
    label: "Selection background",
    description: "Selected text background",
    defaultRole: "accentMuted",
  },
  {
    kind: "workbench",
    category: "Editor",
    id: "editorCursor.foreground",
    label: "Cursor foreground",
    description: "Text cursor color",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Editor",
    id: "editorLineNumber.foreground",
    label: "Line numbers",
    description: "Inactive line numbers",
    defaultRole: "textMuted",
  },
  {
    kind: "workbench",
    category: "Editor",
    id: "editorLineNumber.activeForeground",
    label: "Active line number",
    description: "Current line number",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Editor",
    id: "editorWhitespace.foreground",
    label: "Whitespace",
    description: "Whitespace markers",
    defaultRole: "textMuted",
  },
  {
    kind: "workbench",
    category: "Gutter",
    id: "editorGutter.background",
    label: "Gutter background",
    description: "Editor gutter background",
    defaultRole: "base",
  },
  {
    kind: "workbench",
    category: "Gutter",
    id: "editorGutter.modifiedBackground",
    label: "Modified gutter",
    description: "Modified line marker",
    defaultRole: "diffModified",
  },
  {
    kind: "workbench",
    category: "Gutter",
    id: "editorGutter.addedBackground",
    label: "Added gutter",
    description: "Added line marker",
    defaultRole: "diffAdded",
  },
  {
    kind: "workbench",
    category: "Gutter",
    id: "editorGutter.deletedBackground",
    label: "Deleted gutter",
    description: "Deleted line marker",
    defaultRole: "diffDeleted",
  },
  {
    kind: "workbench",
    category: "Overview",
    id: "editorOverviewRuler.border",
    label: "Overview border",
    description: "Overview ruler border",
    defaultRole: "surfaceAlt",
  },
  {
    kind: "workbench",
    category: "Brackets",
    id: "editorBracketMatch.border",
    label: "Bracket match border",
    description: "Matching bracket border",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Lists",
    id: "list.activeSelectionBackground",
    label: "Active list selection",
    description: "Focused list selection",
    defaultRole: "accentMuted",
  },
  {
    kind: "workbench",
    category: "Lists",
    id: "list.activeSelectionForeground",
    label: "Active list text",
    description: "Focused list text",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Lists",
    id: "list.hoverBackground",
    label: "List hover background",
    description: "Hovered list items",
    defaultRole: "surfaceElevated",
  },
  {
    kind: "workbench",
    category: "Trees",
    id: "tree.indentGuidesStroke",
    label: "Tree guides",
    description: "Tree indent guides",
    defaultRole: "surfaceAlt",
  },
  {
    kind: "workbench",
    category: "Forms",
    id: "input.background",
    label: "Input background",
    description: "Text input background",
    defaultRole: "surfaceElevated",
  },
  {
    kind: "workbench",
    category: "Forms",
    id: "input.foreground",
    label: "Input foreground",
    description: "Text input content",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Forms",
    id: "input.border",
    label: "Input border",
    description: "Input border",
    defaultRole: "accentMuted",
  },
  {
    kind: "workbench",
    category: "Forms",
    id: "button.background",
    label: "Button background",
    description: "Primary button background",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Forms",
    id: "button.foreground",
    label: "Button foreground",
    description: "Primary button text",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Forms",
    id: "button.secondaryBackground",
    label: "Secondary button background",
    description: "Secondary button background",
    defaultRole: "surfaceAlt",
  },
  {
    kind: "workbench",
    category: "Forms",
    id: "dropdown.background",
    label: "Dropdown background",
    description: "Dropdown background",
    defaultRole: "surfaceElevated",
  },
  {
    kind: "workbench",
    category: "Forms",
    id: "checkbox.background",
    label: "Checkbox background",
    description: "Checkbox fill",
    defaultRole: "surfaceElevated",
  },
  {
    kind: "workbench",
    category: "Quick Pick",
    id: "quickInput.background",
    label: "Quick input background",
    description: "Command palette background",
    defaultRole: "surface",
  },
  {
    kind: "workbench",
    category: "Quick Pick",
    id: "quickInput.foreground",
    label: "Quick input foreground",
    description: "Command palette text",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Quick Pick",
    id: "quickInputList.focusBackground",
    label: "Quick input focus",
    description: "Focused command background",
    defaultRole: "accentMuted",
  },
  {
    kind: "workbench",
    category: "Command Center",
    id: "commandCenter.background",
    label: "Command center background",
    description: "Title bar command center",
    defaultRole: "surfaceElevated",
    advanced: true,
  },
  {
    kind: "workbench",
    category: "Panel",
    id: "panel.background",
    label: "Panel background",
    description: "Panel background",
    defaultRole: "base",
  },
  {
    kind: "workbench",
    category: "Panel",
    id: "panelTitle.activeForeground",
    label: "Panel active title",
    description: "Selected panel title",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Notifications",
    id: "notifications.background",
    label: "Notification background",
    description: "Toast and notification background",
    defaultRole: "surface",
  },
  {
    kind: "workbench",
    category: "Notifications",
    id: "notificationLink.foreground",
    label: "Notification link",
    description: "Link color in notifications",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Menu",
    id: "menu.background",
    label: "Menu background",
    description: "Context menu background",
    defaultRole: "surface",
  },
  {
    kind: "workbench",
    category: "Scrollbar",
    id: "scrollbarSlider.background",
    label: "Scrollbar slider",
    description: "Scrollbar handle background",
    defaultRole: "surfaceAlt",
  },
  {
    kind: "workbench",
    category: "Breadcrumb",
    id: "breadcrumb.foreground",
    label: "Breadcrumb foreground",
    description: "Breadcrumb text",
    defaultRole: "textSecondary",
  },
  {
    kind: "workbench",
    category: "Widgets",
    id: "editorWidget.background",
    label: "Widget background",
    description: "Editor widget background",
    defaultRole: "surface",
  },
  {
    kind: "workbench",
    category: "Widgets",
    id: "editorSuggestWidget.selectedBackground",
    label: "Suggest selected background",
    description: "Completion selected row",
    defaultRole: "accentMuted",
  },
  {
    kind: "workbench",
    category: "Widgets",
    id: "editorHoverWidget.background",
    label: "Hover background",
    description: "Hover popup background",
    defaultRole: "surface",
  },
  {
    kind: "workbench",
    category: "Peek",
    id: "peekView.border",
    label: "Peek border",
    description: "Peek view border",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Terminal",
    id: "terminal.background",
    label: "Terminal background",
    description: "Integrated terminal background",
    defaultRole: "base",
  },
  {
    kind: "workbench",
    category: "Terminal",
    id: "terminal.foreground",
    label: "Terminal foreground",
    description: "Integrated terminal text",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Terminal",
    id: "terminalCursor.foreground",
    label: "Terminal cursor",
    description: "Integrated terminal cursor",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Diff",
    id: "diffEditor.insertedTextBackground",
    label: "Diff inserted background",
    description: "Inserted diff text",
    defaultRole: "diffAdded",
  },
  {
    kind: "workbench",
    category: "Diff",
    id: "diffEditor.removedTextBackground",
    label: "Diff removed background",
    description: "Removed diff text",
    defaultRole: "diffDeleted",
  },
  {
    kind: "workbench",
    category: "Git",
    id: "gitDecoration.addedResourceForeground",
    label: "Git added",
    description: "Added resource decoration",
    defaultRole: "diffAdded",
  },
  {
    kind: "workbench",
    category: "Git",
    id: "gitDecoration.modifiedResourceForeground",
    label: "Git modified",
    description: "Modified resource decoration",
    defaultRole: "diffModified",
  },
  {
    kind: "workbench",
    category: "Git",
    id: "gitDecoration.deletedResourceForeground",
    label: "Git deleted",
    description: "Deleted resource decoration",
    defaultRole: "diffDeleted",
  },
  {
    kind: "workbench",
    category: "Symbols",
    id: "symbolIcon.functionForeground",
    label: "Function symbol icon",
    description: "Outline and symbol icon",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Symbols",
    id: "symbolIcon.classForeground",
    label: "Class symbol icon",
    description: "Class symbol icon",
    defaultRole: "accentAlt",
  },
  {
    kind: "workbench",
    category: "Symbols",
    id: "symbolIcon.variableForeground",
    label: "Variable symbol icon",
    description: "Variable symbol icon",
    defaultRole: "textSecondary",
  },
  {
    kind: "workbench",
    category: "Settings",
    id: "settings.headerForeground",
    label: "Settings header",
    description: "Settings header text",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Settings",
    id: "settings.modifiedItemIndicator",
    label: "Settings modified indicator",
    description: "Modified setting marker",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Welcome",
    id: "welcomePage.background",
    label: "Welcome background",
    description: "Welcome page background",
    defaultRole: "base",
    advanced: true,
  },
  {
    kind: "workbench",
    category: "Badges",
    id: "badge.background",
    label: "Badge background",
    description: "Badge background color",
    defaultRole: "accent",
  },
  {
    kind: "workbench",
    category: "Badges",
    id: "badge.foreground",
    label: "Badge foreground",
    description: "Badge text color",
    defaultRole: "textPrimary",
  },
  {
    kind: "workbench",
    category: "Progress",
    id: "progressBar.background",
    label: "Progress background",
    description: "Progress bar color",
    defaultRole: "accent",
  },
];

// TextMate

export const TEXTMATE_EDITABLE_ITEMS: EditableThemeItem[] = [
  {
    kind: "textMate",
    category: "Core",
    id: "comment",
    label: "Comments",
    description: "Code comments",
    defaultRole: "textMuted",
    scopes: ["comment", "punctuation.definition.comment"],
  },
  {
    kind: "textMate",
    category: "Core",
    id: "keyword",
    label: "Keywords",
    description: "Control flow and storage",
    defaultRole: "accent",
    scopes: ["keyword", "storage.type", "storage.modifier"],
  },
  {
    kind: "textMate",
    category: "Core",
    id: "string",
    label: "Strings",
    description: "Quoted text",
    defaultRole: "success",
    scopes: ["string", "string.quoted"],
  },
  {
    kind: "textMate",
    category: "Core",
    id: "number",
    label: "Numbers",
    description: "Numeric literals",
    defaultRole: "warning",
    scopes: ["constant.numeric"],
  },
  {
    kind: "textMate",
    category: "Core",
    id: "constant",
    label: "Constants",
    description: "Named constants",
    defaultRole: "warning",
    scopes: ["constant.language", "constant", "variable.other.constant"],
  },
  {
    kind: "textMate",
    category: "Functions",
    id: "function",
    label: "Functions",
    description: "Function names and calls",
    defaultRole: "accent",
    scopes: ["entity.name.function", "support.function", "variable.function"],
  },
  {
    kind: "textMate",
    category: "Functions",
    id: "parameter",
    label: "Parameters",
    description: "Function parameters",
    defaultRole: "accentAlt",
    scopes: ["variable.parameter", "meta.function.parameter"],
  },
  {
    kind: "textMate",
    category: "Types",
    id: "type",
    label: "Types and classes",
    description: "Class and type names",
    defaultRole: "accentAlt",
    scopes: ["entity.name.type", "entity.name.class", "support.type"],
  },
  {
    kind: "textMate",
    category: "Types",
    id: "interface",
    label: "Interfaces",
    description: "Interfaces and type parameters",
    defaultRole: "accentAlt",
    scopes: ["entity.name.type.interface", "entity.name.type.type-parameter"],
  },
  {
    kind: "textMate",
    category: "Types",
    id: "namespace",
    label: "Namespaces",
    description: "Namespaces and modules",
    defaultRole: "info",
    scopes: ["entity.name.namespace", "entity.name.module", "support.module"],
  },
  {
    kind: "textMate",
    category: "Variables",
    id: "variable",
    label: "Variables",
    description: "General variables",
    defaultRole: "textPrimary",
    scopes: ["variable", "variable.other"],
  },
  {
    kind: "textMate",
    category: "Variables",
    id: "property",
    label: "Properties",
    description: "Object properties",
    defaultRole: "textSecondary",
    scopes: ["variable.other.property", "support.variable.property", "meta.property-name"],
  },
  {
    kind: "textMate",
    category: "Operators",
    id: "operator",
    label: "Operators",
    description: "Operators",
    defaultRole: "accent",
    scopes: ["keyword.operator"],
  },
  {
    kind: "textMate",
    category: "Operators",
    id: "punctuation",
    label: "Punctuation",
    description: "Punctuation and brackets",
    defaultRole: "textSecondary",
    scopes: ["punctuation", "meta.brace", "meta.delimiter"],
  },
  {
    kind: "textMate",
    category: "Markup",
    id: "tag",
    label: "Tags",
    description: "Markup tag names",
    defaultRole: "accent",
    scopes: ["entity.name.tag"],
  },
  {
    kind: "textMate",
    category: "Markup",
    id: "attribute",
    label: "Attributes",
    description: "Markup attribute names",
    defaultRole: "accentAlt",
    scopes: ["entity.other.attribute-name"],
  },
  {
    kind: "textMate",
    category: "Special",
    id: "decorator",
    label: "Decorators",
    description: "Decorators and annotations",
    defaultRole: "info",
    scopes: ["meta.decorator", "entity.name.function.decorator", "storage.type.annotation"],
  },
  {
    kind: "textMate",
    category: "Special",
    id: "regex",
    label: "Regular expressions",
    description: "Regex patterns",
    defaultRole: "info",
    scopes: ["string.regexp", "constant.regexp", "keyword.other.regex"],
  },
  {
    kind: "textMate",
    category: "Special",
    id: "invalid",
    label: "Invalid",
    description: "Invalid syntax",
    defaultRole: "error",
    scopes: ["invalid", "invalid.illegal"],
  },
  {
    kind: "textMate",
    category: "Special",
    id: "deprecated",
    label: "Deprecated",
    description: "Deprecated syntax",
    defaultRole: "warning",
    scopes: ["invalid.deprecated"],
  },
];

// Semantic

export const SEMANTIC_EDITABLE_ITEMS: EditableThemeItem[] = [
  ["namespace", "Types", "Namespaces", "Namespace symbols", "info"],
  ["class", "Types", "Classes", "Class declarations", "accentAlt"],
  ["enum", "Types", "Enums", "Enum declarations", "warning"],
  ["interface", "Types", "Interfaces", "Interface declarations", "accentAlt"],
  ["struct", "Types", "Structs", "Struct declarations", "accentAlt"],
  ["type", "Types", "Types", "General types", "accentAlt"],
  ["typeParameter", "Types", "Type parameters", "Generic type parameters", "info"],
  ["parameter", "Functions", "Parameters", "Semantic parameters", "accentAlt"],
  ["variable", "Variables", "Variables", "Semantic variables", "textPrimary"],
  ["variable.readonly", "Variables", "Readonly variables", "Readonly variables", "warning"],
  ["property", "Variables", "Properties", "Semantic properties", "textSecondary"],
  ["property.readonly", "Variables", "Readonly properties", "Readonly properties", "warning"],
  ["enumMember", "Variables", "Enum members", "Enum members", "warning"],
  ["event", "Functions", "Events", "Event symbols", "info"],
  ["function", "Functions", "Functions", "Function declarations", "accent"],
  ["method", "Functions", "Methods", "Method declarations", "accent"],
  ["macro", "Functions", "Macros", "Macro symbols", "error"],
  ["keyword", "Core", "Keywords", "Semantic keywords", "accent"],
  ["comment", "Core", "Comments", "Semantic comments", "textMuted"],
  ["string", "Core", "Strings", "Semantic strings", "success"],
  ["number", "Core", "Numbers", "Semantic numbers", "warning"],
  ["regexp", "Core", "Regex", "Semantic regex", "info"],
  ["operator", "Core", "Operators", "Semantic operators", "accent"],
  ["decorator", "Core", "Decorators", "Semantic decorators", "info"],
  ["*.declaration", "Advanced", "Declarations", "All declarations", "textPrimary"],
  ["*.static", "Advanced", "Static symbols", "All static symbols", "info"],
  ["*.defaultLibrary", "Advanced", "Default library", "Default library symbols", "textMuted"],
  ["*.deprecated", "Advanced", "Deprecated symbols", "Deprecated semantic symbols", "warning"],
].map(
  ([id, category, label, description, defaultRole]) =>
    ({
      kind: "semantic",
      category,
      id,
      label,
      description,
      defaultRole: defaultRole as ThemeRoleName,
      semanticSelector: id,
      advanced: category === "Advanced",
    }) satisfies EditableThemeItem,
);

export const ALL_EDITABLE_ITEMS: EditableThemeItem[] = [
  ...WORKBENCH_EDITABLE_ITEMS,
  ...TEXTMATE_EDITABLE_ITEMS,
  ...SEMANTIC_EDITABLE_ITEMS,
];

export function getEditableItemsByKind(
  kind: EditableThemeItemKind,
): EditableThemeItem[] {
  return ALL_EDITABLE_ITEMS.filter((item) => item.kind === kind);
}
